name: Build for release
on: 
  release:
    types: prereleased
jobs:
    build:
      runs-on: windows-latest
      steps:
        - name: checkout repo 
          uses: actions/checkout@v2
        - name: setup dotnet 
          uses: actions/setup-dotnet@v1
          with:
            dotnet-version: '6.0.x'
        - name: Add msbuild to PATH
          uses: microsoft/setup-msbuild@v1.1
          with:
            msbuild-architecture: x64
        - run: "nuget restore ${env:GITHUB_WORKSPACE}\\cs-windows-firewall-bouncer.sln"
        - name: Build release bouncer
          run: "msbuild ${env:GITHUB_WORKSPACE}\\cs-windows-firewall-bouncer.sln -t:rebuild -property:Configuration=Release"
        - name: Upload to release
          uses: JasonEtco/upload-to-release@master
          with:
            args: "cs-windows-firewall-bouncer-setup\\bin\\x64\\Release\\cs_windows_firewall_bouncer_setup.msi application/octet-stream"
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}